from enum import Enum
from pydantic import BaseModel, Field
from typing import List, Optional

class RelationshipType(str, Enum):
    ACQUIRED = "ACQUIRED"
    SUED = "SUED"
    PARTNERED = "PARTNERED"
    INVESTED = "INVESTED"
    DIVESTED = "DIVESTED"
    HIRED = "HIRED"
    REGULATED = "REGULATED"
    LAUNCHED_PRODUCT = "LAUNCHED_PRODUCT"
    EXPANDED = "EXPANDED"
    CLOSED = "CLOSED"
    REPORTED_FINANCIALS = "REPORTED_FINANCIALS"
    ISSUED_GUIDANCE = "ISSUED_GUIDANCE"
    DECLARED_DIVIDEND = "DECLARED_DIVIDEND"
    AUTHORIZED_BUYBACK = "AUTHORIZED_BUYBACK"
    ISSUED_DEBT = "ISSUED_DEBT"
    DEFAULTED = "DEFAULTED"
    FILED_BANKRUPTCY = "FILED_BANKRUPTCY"
    SETTLED_LEGAL_DISPUTE = "SETTLED_LEGAL_DISPUTE"
    GRANTED_PATENT = "GRANTED_PATENT"
    RECALLED_PRODUCT = "RECALLED_PRODUCT"
    EXPERIENCED_DATA_BREACH = "EXPERIENCED_DATA_BREACH"
    EXECUTIVE_RESIGNATION = "EXECUTIVE_RESIGNATION"
    ANALYST_RATING_CHANGE = "ANALYST_RATING_CHANGE"
    # Macro / Economic
    RAISED_POLICY_RATE = "RAISED_POLICY_RATE"
    LOWERED_POLICY_RATE = "LOWERED_POLICY_RATE"
    REPORTED_ECONOMIC_DATA = "REPORTED_ECONOMIC_DATA"
    IMPOSED_SANCTIONS = "IMPOSED_SANCTIONS"
    # Subsidiary / Structure
    ESTABLISHED_SUBSIDIARY = "ESTABLISHED_SUBSIDIARY"
    INTEGRATED_SUBSIDIARY = "INTEGRATED_SUBSIDIARY"
    SPUN_OFF = "SPUN_OFF"
    # Beige Book / Deep Trader Signals
    REPORTED_WAGE_PRESSURE_EASING = "REPORTED_WAGE_PRESSURE_EASING"
    REPORTED_WAGE_PRESSURE_RISING = "REPORTED_WAGE_PRESSURE_RISING"
    REPORTED_LABOR_MARKET_SOFTENING = "REPORTED_LABOR_MARKET_SOFTENING"
    REPORTED_PRICING_POWER_EROSION = "REPORTED_PRICING_POWER_EROSION"
    REPORTED_CONSUMER_TRADING_DOWN = "REPORTED_CONSUMER_TRADING_DOWN"
    REPORTED_CREDIT_QUALITY_DETERIORATION = "REPORTED_CREDIT_QUALITY_DETERIORATION"
    REPORTED_LENDING_STANDARDS_TIGHTENING = "REPORTED_LENDING_STANDARDS_TIGHTENING"
    REPORTED_CRE_DISTRESS = "REPORTED_CRE_DISTRESS"
    REPORTED_INVENTORY_BUILDUP = "REPORTED_INVENTORY_BUILDUP"
    REPORTED_CAPEX_DELAY = "REPORTED_CAPEX_DELAY"
    REPORTED_OUTLOOK_UNCERTAINTY = "REPORTED_OUTLOOK_UNCERTAINTY"
    # Beige Book / General Categories
    REPORTED_ECONOMIC_ACTIVITY = "REPORTED_ECONOMIC_ACTIVITY"
    REPORTED_LABOR_CONDITIONS = "REPORTED_LABOR_CONDITIONS"
    REPORTED_WAGE_TRENDS = "REPORTED_WAGE_TRENDS"
    REPORTED_PRICE_PRESSURES = "REPORTED_PRICE_PRESSURES"
    REPORTED_CONSUMER_SPENDING = "REPORTED_CONSUMER_SPENDING"
    REPORTED_CREDIT_CONDITIONS = "REPORTED_CREDIT_CONDITIONS"
    REPORTED_REAL_ESTATE = "REPORTED_REAL_ESTATE"
    # Causal
    CAUSED = "CAUSED"
    EFFECTED_BY = "EFFECTED_BY"
    CONTRIBUTED_TO = "CONTRIBUTED_TO"
    PREVENTED = "PREVENTED"
    # Attribute Relationships (Entity properties stored as edges)
    HEADQUARTERED_IN = "HEADQUARTERED_IN"
    HAS_TICKER = "HAS_TICKER"
    TRADES_ON = "TRADES_ON"
    HAS_MOTTO = "HAS_MOTTO"
    FOUNDED_IN = "FOUNDED_IN"
    OPERATES_IN = "OPERATES_IN"
    HAS_WEBSITE = "HAS_WEBSITE"
    LED_BY = "LED_BY"
    OFFERS_PRODUCT = "OFFERS_PRODUCT"
    PROVIDES_SERVICE = "PROVIDES_SERVICE"
    # Disclosure / Revelation Relationships
    REVEALED = "REVEALED"
    DISCLOSED = "DISCLOSED"
    ANNOUNCED = "ANNOUNCED"
    # Inspiration / Influence Relationships
    INSPIRED_BY = "INSPIRED_BY"
    MODELED_AFTER = "MODELED_AFTER"
    # Advisory Relationships
    ENCOURAGED = "ENCOURAGED"
    ADVISED = "ADVISED"
    RECOMMENDED = "RECOMMENDED"

class RelationshipDefinition(BaseModel):
    name: RelationshipType
    description: str
    examples: List[str]

class RelationshipClassification(BaseModel):
    relationship: RelationshipType = Field(..., description="The classified relationship type.")
    confidence: float = Field(..., description="Confidence score between 0 and 1.")

# Active to Passive Mapping
ACTIVE_TO_PASSIVE = {
    # Corporate Actions
    RelationshipType.ACQUIRED: "GOT_ACQUIRED",
    RelationshipType.SUED: "GOT_SUED",
    RelationshipType.PARTNERED: "PARTNERED_WITH",
    RelationshipType.INVESTED: "RECEIVED_INVESTMENT",
    RelationshipType.DIVESTED: "WAS_DIVESTED",
    RelationshipType.HIRED: "WAS_HIRED",
    RelationshipType.LAUNCHED_PRODUCT: "WAS_LAUNCHED",
    RelationshipType.EXPANDED: "WAS_EXPANDED_INTO",
    RelationshipType.CLOSED: "WAS_CLOSED",
    
    # Financial
    RelationshipType.REPORTED_FINANCIALS: "FINANCIALS_REPORTED_BY",
    RelationshipType.ISSUED_GUIDANCE: "GUIDANCE_ISSUED_BY",
    RelationshipType.DECLARED_DIVIDEND: "DIVIDEND_DECLARED_BY",
    RelationshipType.AUTHORIZED_BUYBACK: "BUYBACK_AUTHORIZED_BY",
    RelationshipType.ISSUED_DEBT: "DEBT_ISSUED_BY",
    RelationshipType.DEFAULTED: "DEFAULTED_ON",
    RelationshipType.FILED_BANKRUPTCY: "BANKRUPTCY_FILED_BY",
    
    # Regulatory / Legal
    RelationshipType.SETTLED_LEGAL_DISPUTE: "LEGAL_DISPUTE_SETTLED_BY",
    RelationshipType.GRANTED_PATENT: "PATENT_GRANTED_To",
    RelationshipType.RECALLED_PRODUCT: "PRODUCT_RECALLED_BY",
    RelationshipType.EXPERIENCED_DATA_BREACH: "DATA_BREACH_EXPERIENCED_BY",
    RelationshipType.REGULATED: "GOT_REGULATED",
    
    # Executive / Analyst
    RelationshipType.EXECUTIVE_RESIGNATION: "RESIGNATION_FROM",
    RelationshipType.ANALYST_RATING_CHANGE: "RATING_CHANGED_BY",
    
    # Macro
    RelationshipType.RAISED_POLICY_RATE: "AFFECTED_BY_RATE_HIKE",
    RelationshipType.LOWERED_POLICY_RATE: "AFFECTED_BY_RATE_CUT",
    RelationshipType.REPORTED_ECONOMIC_DATA: "DATA_REPORTED_IN",
    RelationshipType.IMPOSED_SANCTIONS: "SANCTIONED_BY",
    
    # Subsidiary
    RelationshipType.ESTABLISHED_SUBSIDIARY: "ESTABLISHED_BY",
    RelationshipType.INTEGRATED_SUBSIDIARY: "INTEGRATED_INTO",
    RelationshipType.SPUN_OFF: "SPUN_OFF_FROM",
    
    # Beige Book (Signals usually apply to the region/topic, so passive might be vague)
    # Using generic "SIGNALED_IN" pattern or specific
    RelationshipType.REPORTED_WAGE_PRESSURE_EASING: "WAGE_PRESSURE_EASING_REPORTED_IN",
    RelationshipType.REPORTED_WAGE_PRESSURE_RISING: "WAGE_PRESSURE_RISING_REPORTED_IN",
    RelationshipType.REPORTED_LABOR_MARKET_SOFTENING: "LABOR_MARKET_SOFTENING_REPORTED_IN",
    RelationshipType.REPORTED_PRICING_POWER_EROSION: "PRICING_POWER_EROSION_REPORTED_IN",
    RelationshipType.REPORTED_CONSUMER_TRADING_DOWN: "CONSUMER_TRADING_DOWN_REPORTED_IN",
    RelationshipType.REPORTED_CREDIT_QUALITY_DETERIORATION: "CREDIT_QUALITY_DETERIORATION_REPORTED_IN",
    RelationshipType.REPORTED_LENDING_STANDARDS_TIGHTENING: "LENDING_STANDARDS_TIGHTENING_REPORTED_IN",
    RelationshipType.REPORTED_CRE_DISTRESS: "CRE_DISTRESS_REPORTED_IN",
    RelationshipType.REPORTED_INVENTORY_BUILDUP: "INVENTORY_BUILDUP_REPORTED_IN",
    RelationshipType.REPORTED_CAPEX_DELAY: "CAPEX_DELAY_REPORTED_IN",
    RelationshipType.REPORTED_OUTLOOK_UNCERTAINTY: "OUTLOOK_UNCERTAINTY_REPORTED_IN",
    
    RelationshipType.REPORTED_ECONOMIC_ACTIVITY: "ECONOMIC_ACTIVITY_REPORTED_IN",
    RelationshipType.REPORTED_LABOR_CONDITIONS: "LABOR_CONDITIONS_REPORTED_IN",
    RelationshipType.REPORTED_WAGE_TRENDS: "WAGE_TRENDS_REPORTED_IN",
    RelationshipType.REPORTED_PRICE_PRESSURES: "PRICE_PRESSURES_REPORTED_IN",
    RelationshipType.REPORTED_CONSUMER_SPENDING: "CONSUMER_SPENDING_REPORTED_IN",
    RelationshipType.REPORTED_CREDIT_CONDITIONS: "CREDIT_CONDITIONS_REPORTED_IN",
    RelationshipType.REPORTED_REAL_ESTATE: "REAL_ESTATE_REPORTED_IN",
    
    # Causal (These are usually Fact->Fact, but if Entity involved...)
    RelationshipType.CAUSED: "CAUSED_BY",
    RelationshipType.EFFECTED_BY: "EFFECT_OF",
    RelationshipType.CONTRIBUTED_TO: "CONTRIBUTED_TO_BY",
    RelationshipType.PREVENTED: "PREVENTED_BY",
    # Attribute Relationships
    RelationshipType.HEADQUARTERED_IN: "HEADQUARTERS_OF",
    RelationshipType.HAS_TICKER: "TICKER_OF",
    RelationshipType.TRADES_ON: "LISTS",
    RelationshipType.HAS_MOTTO: "MOTTO_OF",
    RelationshipType.FOUNDED_IN: "FOUNDING_OF",
    RelationshipType.OPERATES_IN: "OPERATION_REGION_OF",
    RelationshipType.HAS_WEBSITE: "WEBSITE_OF",
    RelationshipType.LED_BY: "LEADS",
    RelationshipType.OFFERS_PRODUCT: "PRODUCT_OF",
    RelationshipType.PROVIDES_SERVICE: "SERVICE_OF",
    # Disclosure / Revelation
    RelationshipType.REVEALED: "REVEALED_BY",
    RelationshipType.DISCLOSED: "DISCLOSED_BY",
    RelationshipType.ANNOUNCED: "ANNOUNCED_BY",
    # Inspiration / Influence
    RelationshipType.INSPIRED_BY: "INSPIRED",
    RelationshipType.MODELED_AFTER: "MODEL_FOR",
    # Advisory
    RelationshipType.ENCOURAGED: "ENCOURAGED_BY",
    RelationshipType.ADVISED: "ADVISED_BY",
    RelationshipType.RECOMMENDED: "RECOMMENDED_BY",
}
