from enum import Enum
from pydantic import BaseModel, Field
from typing import List, Optional

class RelationshipType(str, Enum):
    ACQUIRED = "ACQUIRED"
    SUED = "SUED"
    PARTNERED = "PARTNERED"
    INVESTED = "INVESTED"
    DIVESTED = "DIVESTED"
    HIRED = "HIRED"
    REGULATED = "REGULATED"
    LAUNCHED_PRODUCT = "LAUNCHED_PRODUCT"
    EXPANDED = "EXPANDED"
    CLOSED = "CLOSED"
    REPORTED_FINANCIALS = "REPORTED_FINANCIALS"
    ISSUED_GUIDANCE = "ISSUED_GUIDANCE"
    DECLARED_DIVIDEND = "DECLARED_DIVIDEND"
    AUTHORIZED_BUYBACK = "AUTHORIZED_BUYBACK"
    ISSUED_DEBT = "ISSUED_DEBT"
    DEFAULTED = "DEFAULTED"
    FILED_BANKRUPTCY = "FILED_BANKRUPTCY"
    SETTLED_LEGAL_DISPUTE = "SETTLED_LEGAL_DISPUTE"
    GRANTED_PATENT = "GRANTED_PATENT"
    RECALLED_PRODUCT = "RECALLED_PRODUCT"
    EXPERIENCED_DATA_BREACH = "EXPERIENCED_DATA_BREACH"
    EXECUTIVE_RESIGNATION = "EXECUTIVE_RESIGNATION"
    ANALYST_RATING_CHANGE = "ANALYST_RATING_CHANGE"
    # Macro / Economic
    RAISED_POLICY_RATE = "RAISED_POLICY_RATE"
    LOWERED_POLICY_RATE = "LOWERED_POLICY_RATE"
    REPORTED_ECONOMIC_DATA = "REPORTED_ECONOMIC_DATA"
    IMPOSED_SANCTIONS = "IMPOSED_SANCTIONS"
    # Subsidiary / Structure
    ESTABLISHED_SUBSIDIARY = "ESTABLISHED_SUBSIDIARY"
    INTEGRATED_SUBSIDIARY = "INTEGRATED_SUBSIDIARY"
    SPUN_OFF = "SPUN_OFF"
    # Beige Book / Deep Trader Signals
    REPORTED_WAGE_PRESSURE_EASING = "REPORTED_WAGE_PRESSURE_EASING"
    REPORTED_WAGE_PRESSURE_RISING = "REPORTED_WAGE_PRESSURE_RISING"
    REPORTED_LABOR_MARKET_SOFTENING = "REPORTED_LABOR_MARKET_SOFTENING"
    REPORTED_PRICING_POWER_EROSION = "REPORTED_PRICING_POWER_EROSION"
    REPORTED_CONSUMER_TRADING_DOWN = "REPORTED_CONSUMER_TRADING_DOWN"
    REPORTED_CREDIT_QUALITY_DETERIORATION = "REPORTED_CREDIT_QUALITY_DETERIORATION"
    REPORTED_LENDING_STANDARDS_TIGHTENING = "REPORTED_LENDING_STANDARDS_TIGHTENING"
    REPORTED_CRE_DISTRESS = "REPORTED_CRE_DISTRESS"
    REPORTED_INVENTORY_BUILDUP = "REPORTED_INVENTORY_BUILDUP"
    REPORTED_CAPEX_DELAY = "REPORTED_CAPEX_DELAY"
    REPORTED_OUTLOOK_UNCERTAINTY = "REPORTED_OUTLOOK_UNCERTAINTY"
    # Beige Book / General Categories
    REPORTED_ECONOMIC_ACTIVITY = "REPORTED_ECONOMIC_ACTIVITY"
    REPORTED_LABOR_CONDITIONS = "REPORTED_LABOR_CONDITIONS"
    REPORTED_WAGE_TRENDS = "REPORTED_WAGE_TRENDS"
    REPORTED_PRICE_PRESSURES = "REPORTED_PRICE_PRESSURES"
    REPORTED_CONSUMER_SPENDING = "REPORTED_CONSUMER_SPENDING"
    REPORTED_CREDIT_CONDITIONS = "REPORTED_CREDIT_CONDITIONS"
    REPORTED_REAL_ESTATE = "REPORTED_REAL_ESTATE"
    # Causal
    CAUSED = "CAUSED"
    EFFECTED_BY = "EFFECTED_BY"
    CONTRIBUTED_TO = "CONTRIBUTED_TO"
    PREVENTED = "PREVENTED"

class RelationshipDefinition(BaseModel):
    name: RelationshipType
    description: str
    examples: List[str]

class RelationshipClassification(BaseModel):
    relationship: RelationshipType = Field(..., description="The classified relationship type.")
    confidence: float = Field(..., description="Confidence score between 0 and 1.")
